version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend-network
  
  mini-project-backend:
    container_name: mini-project-backend
    image: miniprojectbedev:latest
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - CONFIG_DATABASE=${CONFIG_DATABASE}
      - CONFIG_HOST=${CONFIG_HOST}

networks:
  backend-network:
    name: backend-network
